# == This is the global Alchemy configuration file
# Please override settings for your app in RAILS_ROOT/config/alchemy/config.yml of your application.

:show_rootname: a name
:mailer:
    :forward_to_page: false
    :mail_sucess_page: root
    :mail_from: 'alchemy <mail@alchemy.com>'
:visible: true
:sitemap: 
  :show_root: true
  :show_flag: false
:auto_logout_time: 10
:redirect_index: true
:redirect_to_public_child: true

# Ferret fulltext search.
:ferret: true

# Page caching. Pass false to disable it globally.
:cache_pages: true

# Picture settings
:output_image_jpg_quality: 85
:preprocess_image_resize: 1000x1000
:image_store_format: png
:image_output_format: jpg

# Language settings
:default_language: de
:default_alchemy_language: de
:show_real_root: false
:languages:
  - :language_code: de
    :language: Deutsch
    :frontpage_name: Startseite
    :page_layout: intro
  - :language_code: en
    :language: English
    :frontpage_name: Frontpage
    :page_layout: intro

# Set available translations for your customers.
:translations:
  - :language_code: de
    :language: Deutsch
  - :language_code: en
    :language: English

# Contactform settings
:mailer:
  :form_layout_name: contact
  :fields:
    - salutation: string
    - firstname: string
    - lastname: string
    - address: string
    - zip: string
    - city: string
    - phone: string
    - email: string
    - message: text
  :validate_fields:
    :lastname:
      :message: blank_lastname
    :email:
      :message: blank_email

# User roles.
:user_roles: [registered, author, editor, admin]

# == This is the Alchemy plugin configuration.
# To render the mainnavigation we split Alchemy into three plugins.
# To make an own plugin just make a new folder in vendor/plugins and put an init.rb file in it and a config
# folder with a Alchemy folder in it. Place a config.yml in this Alchemy folder.
#
# vendor/plugins/MY_PLUGIN_NAME/init.rb
# vendor/plugins/MY_PLUGIN_NAME/config/alchemy/config.yml
#
# Example config.yml
# 
# name: PLUGIN_NAME
# settings: PUT SOME SETTINGS HERE
# preview_frame: IF YOU WANT TO USE THE ALCHEMY PREVIEW FRAME!
# navigation:
#   name: NAME IN ALCHEMY NAVIGATION
#   controller: controller_name
#   action: action_of_controller
#   image: /plugin_assets/PLUGIN_NAME/images/NAVIGATION_IMAGE.png
#   sub_navigation:
#     - name: subnavigation_entry
#       controller: controller_name
#       action: action_of_controller
#     - name: subnavigation_entry
#       controller: controller_name
#       action: action_of_controller
#     - name: subnavigation_entry
#       controller: controller_name
#       action: action_of_controller

alchemy_plugins:

  - name: dashboard
    navigation:
      name: 'home'
      controller: admin
      action: index
      image: /images/alchemy/icons/home.png
      sub_navigation:
        - name: 'home'
          controller: admin
          action: index
    
  - name: pages
    preview_frame:
      controller: 'admin/pages'
      action: edit
      target_controller: 'admin/pages'
      target_action: preview
    navigation:
      name: 'module: pages'
      controller: 'admin/pages'
      action: index
      image: /images/alchemy/icons/pages.png
      sub_navigation:
        - name: 'module: pages'
          controller: 'admin/pages'
          action: index
        - name: 'module: layoutpages'
          controller: 'admin/pages'
          action: layoutpages
      nested:
        - controller: 'admin/pages'
          action: edit

  - name: users
    navigation:
      name: 'module: users'
      controller: 'admin/users'
      action: index
      image: /images/alchemy/icons/users.png
      sub_navigation:
        - name: 'module: users'
          controller: 'admin/users'
          action: index
        
  - name: archive
    navigation:
      controller: 'admin/pictures'
      action: index
      name: 'module: library'
      image: /images/alchemy/icons/library.png
      sub_navigation:
        - name: 'module: images'
          controller: 'admin/pictures'
          action: index
        - name: 'module: attachments'
          controller: 'admin/attachments'
          action: index
