- name: article
  display_name: Artikelabsatz
  contents:
  - name: headline
    type: EssenceText
  - name: text
    type: EssenceRichtext

- name: text
  display_name: Text
  contents:
  - name: text
    type: EssenceRichtext

- name: headline
  display_name: Überschrift
  contents:
  - name: headline
    type: EssenceText

- name: subheadline
  display_name: Zwischenüberschrift
  contents:
  - name: headline
    type: EssenceText

- name: news
  display_name: News
  contents:
  - name: date
    type: EssenceDate
  - name: headline
    type: EssenceText
  - name: body
    type: EssenceRichtext

- name: searchresult
  display_name: Suchergebnis

- name: contactform
  display_name: Kontaktformular
  contents:
  - name: mail_from
    type: EssenceText
  - name: mail_to
    type: EssenceText
  - name: subject
    type: EssenceText
  - name: success_page
    type: EssenceText
  
- name: gallery
  display_name: Bildergalerie
