- name: article
  display_name: Artikelabsatz
  contents:
  - name: intro
    type: EssenceText
  - name: headline
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: text
    type: EssenceRichtext

- name: text
  display_name: Text
  contents:
  - name: text
    type: EssenceRichtext

- name: headline
  display_name: Überschrift
  contents:
  - name: headline
    type: EssenceText

- name: intro
  display_name: Introtext
  contents: 
  - name: intro
    type: EssenceRichtext

- name: subheadline
  display_name: Zwischenüberschrift
  contents:
  - name: headline
    type: EssenceText

- name: news
  display_name: News
  contents:
  - name: date
    type: EssenceDate
  - name: headline
    type: EssenceText
  - name: body
    type: EssenceRichtext

- name: searchresult
  unique: true
  display_name: Suchergebnis

- name: contactform
  display_name: Kontaktformular
  unique: true
  contents:
  - name: mail_from
    type: EssenceText
  - name: mail_to
    type: EssenceText
  - name: subject
    type: EssenceText
  - name: success_page
    type: EssenceText
  
- name: gallery
  display_name: Bildergalerie

- name: newsletter_article
  display_name: Artikel
  contents:
  - name: headline
    type: EssenceText
  - name: text
    type: EssenceRichtext

- name: newsletter_intro
  display_name: Intro
  unique: true
  contents:
  - name: text
    type: EssenceRichtext
