# == Alchemy core modules configuration

- name: dashboard
  navigation:
    name: 'home'
    controller: 'admin'
    action: index
    icon: home
    sub_navigation:
      - name: 'home'
        controller: 'admin'
        action: index

- name: pages
  navigation:
    name: 'module: pages'
    controller: 'admin/pages'
    action: index
    icon: pages
    sub_navigation:
      - name: 'module: pages'
        controller: 'admin/pages'
        action: index
      - name: 'module: layoutpages'
        controller: 'admin/layoutpages'
        action: index
    nested:
      - controller: 'admin/pages'
        action: edit

- name: languages
  navigation:
    name: 'module: languages'
    controller: 'admin/languages'
    action: index
    icon: languages
    sub_navigation:
      - name: 'module: languages'
        controller: 'admin/languages'
        action: index

- name: users
  navigation:
    name: 'module: users'
    controller: 'admin/users'
    action: index
    icon: users
    sub_navigation:
      - name: 'module: users'
        controller: 'admin/users'
        action: index

- name: archive
  navigation:
    controller: 'admin/pictures'
    action: index
    name: 'module: library'
    icon: library
    sub_navigation:
      - name: 'module: pictures'
        controller: 'admin/pictures'
        action: index
      - name: 'module: attachments'
        controller: 'admin/attachments'
        action: index
