- name: standard
  display_name: Standard
  elements: [headline, text, subheadline, article, gallery]
  autogenerate: [headline, article]

- name: contact
  display_name: Kontakt
  unique: true
  cache: false
  elements: [headline, text, contactform]
  autogenerate: [headline, text, contactform]

- name: news
  display_name: News
  feed: true
  elements: [headline, news]
  autogenerate: [news]

- name: search
  display_name: Suche
  unique: true
  cache: false
  elements: [headline, text, searchresult]
  autogenerate: [searchresult]

- name: system_header
  display_name: System Header
  unique: true
  hide: true
  elements:

- name: system_footer
  display_name: System Footer
  unique: true
  hide: true
  elements:
