language: ruby
rvm:
  - ree
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "phantomjs -v"
  - "sh -c 'cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:schema:load --trace'"
script: "bundle exec rspec spec"
env:
  - DB=mysql
  - DB=postgresql
