language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-19mode
branches:
  only:
    - master
before_script:
  - "sh -c 'cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:schema:load --trace'"
script: "bundle exec rspec spec"
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
matrix:
  allow_failures:
    - rvm: rbx-19mode
