language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
script: rake
env:
  - DB=mysql
  - DB=postgresql
notifications:
  irc:
    on_success: change
    on_failure: always
    use_notice: true
    channels:
      - "irc.freenode.org#alchemy_cms"
before_install:
  - gem install bundler -v '= 1.5.1'
