rvm:
  - 1.8.7
branches:
  only:
    - next_stable
before_script:
  - "mysql -e 'create database alchemy_cms_test;'"
  - "cd spec/dummy && bundle exec rake db:create db:migrate db:seed" 
env:
  - DB=mysql
