language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
branches:
  only:
    - 3.0-stable
before_script: 'bundle exec rake alchemy:spec:prepare'
script: 'bundle exec rspec'
env:
  - DB=mysql
  - DB=postgresql
  - RAILS_VERSION=4.0.13
notifications:
  irc:
    on_success: change
    on_failure: always
    use_notice: true
    channels:
      - "irc.freenode.org#alchemy_cms"
