language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - ree
branches:
  only:
    - 2.1-stable
before_script:
  - "sh -c 'cd spec/dummy; RAILS_ENV=test bundle exec rake db:reset'"
script: "bundle exec rspec spec"
