--- 
javascripts:
  - jquery
  - jquery-ui
  - jquery.dialogextend.min.js
  - jquery.in-place-edit.js
  - jquery.Jcrop.min.js
  - jquery.sb.min.js
  - jquery.scrollTo-1.4.2-min.js
  - jquery.ui.nestedSortable.js
  - jquery.ui.tabspaging.js
  - alchemy
  - alchemy.element_editor_selector
  - alchemy.image_cropper
  - alchemy.link_overlay
  - alchemy.page_sorter
  - alchemy.growler
  - swfupload/swfupload
  - swfupload/queue
  - swfupload/handlers
  - swfupload/fileprogress

stylesheets:
  - alchemy
  - elements
  - flags
  - jquery-ui-1.8.7.alchemy.css
  - jquery.Jcrop
  - jquery.sb
