--- 
javascripts:
- default:
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/jquery.sb.min
  - alchemy/alchemy_frame_set
- login:
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/jquery.sb.min
  - alchemy/alchemy_frame_set
- sitemap:
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/jquery.sb.min
  - alchemy/alchemy_frame_set
  - alchemy/jquery.ui.nestedSortable
- edit_page:
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/jquery.sb.min
  - alchemy/alchemy_frame_set
  - alchemy/alchemy_element_editor_selector
  - alchemy/alchemy_image_cropper
  - alchemy/swfupload/swfupload
  - alchemy/swfupload/handlers
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/queue
- preview:
  - alchemy/jquery-1.4.4.min
  - alchemy/alchemy_element_selector
- archive:
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/jquery.in-place-edit
  - alchemy/alchemy
  - alchemy/jquery.sb.min
  - alchemy/alchemy_frame_set
  - alchemy/swfupload/swfupload
  - alchemy/swfupload/handlers
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/queue

stylesheets:
- default:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/jquery-ui-1.8.7.alchemy.css
  - alchemy/jquery.sb
- login:
  - alchemy/alchemy
  - alchemy/alchemy_login
  - alchemy/alchemy_window
  - alchemy/jquery-ui-1.8.7.alchemy.css
  - alchemy/jquery.sb
- sitemap:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/jquery-ui-1.8.7.alchemy.css
  - alchemy/jquery.sb
- edit_page:
  - alchemy/alchemy
  - alchemy/elements
  - alchemy/contents
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/cropper
  - alchemy/flags
  - alchemy/jquery-ui-1.8.7.alchemy.css
  - alchemy/jquery.sb
- archive:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/jquery-ui-1.8.7.alchemy.css
  - alchemy/jquery.sb
