--- 
javascripts:
- combined:
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/jquery.dialogextend.min
  - alchemy/jquery.in-place-edit.js
  - alchemy/jquery.Jcrop.min
  - alchemy/jquery.sb.min
  - alchemy/jquery.scrollTo-1.4.2-min
  - alchemy/jquery.ui.nestedSortable
  - alchemy/alchemy
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/handlers
  - alchemy/swfupload/queue
  - alchemy/swfupload/swfupload
- preview:
  - alchemy/jquery-1.4.4.min
  - alchemy/alchemy

stylesheets:
- combined:
  - alchemy/alchemy
  - alchemy/elements
  - alchemy/flags
  - alchemy/jquery-ui-1.8.7.alchemy.css
  - alchemy/jquery.Jcrop
  - alchemy/jquery.sb
