--- 
javascripts:
- default:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/window
  - alchemy/window_effects
  - alchemy/alchemy_frame_set
- login:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/window
  - alchemy/window_effects
  - alchemy/alchemy
  - alchemy/alchemy_frame_set
- sitemap:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/window
  - alchemy/window_effects
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
  - alchemy/tooltip
  - alchemy/dragdrop
  - alchemy/sortable_tree
- edit_page:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/controls
  - alchemy/slider
  - alchemy/livepipe
  - alchemy/scrollbar
  - alchemy/dragdrop
  - alchemy/window
  - alchemy/window_effects
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
  - alchemy/alchemy_element_editor_selector
  - alchemy/cropper
  - alchemy/alchemy_image_cropper
  - alchemy/swfupload/swfupload
  - alchemy/swfupload/handlers
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/queue
- preview:
  - alchemy/prototype
  - alchemy/alchemy_element_selector
- archive:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/controls
  - alchemy/window
  - alchemy/window_effects
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
  - alchemy/swfupload/swfupload
  - alchemy/swfupload/handlers
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/queue

stylesheets:
- default:
  - alchemy/alchemy
  - alchemy/alchemy_window
- login:
  - alchemy/alchemy
  - alchemy/alchemy_login
  - alchemy/alchemy_window
- sitemap:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
- edit_page:
  - alchemy/alchemy
  - alchemy/elements
  - alchemy/contents
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/cropper
- archive:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
