--- 
javascripts:
- default:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
- login:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
- sitemap:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
  - alchemy/tooltip
  - alchemy/dragdrop
  - alchemy/sortable_tree
- edit_page:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/controls
  - alchemy/slider
  - alchemy/livepipe
  - alchemy/scrollbar
  - alchemy/dragdrop
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
  - alchemy/alchemy_element_editor_selector
  - alchemy/cropper
  - alchemy/alchemy_image_cropper
  - alchemy/swfupload/swfupload
  - alchemy/swfupload/handlers
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/queue
- preview:
  - alchemy/prototype
  - alchemy/alchemy_element_selector
- archive:
  - alchemy/prototype
  - alchemy/effects
  - alchemy/jquery-1.4.4.min
  - alchemy/jquery-ui-1.8.7.min
  - alchemy/jquery.in-place-edit
  - alchemy/controls
  - alchemy/alchemy
  - alchemy/alchemy_selectbox
  - alchemy/alchemy_frame_set
  - alchemy/swfupload/swfupload
  - alchemy/swfupload/handlers
  - alchemy/swfupload/fileprogress
  - alchemy/swfupload/queue

stylesheets:
- default:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/jquery-ui-1.8.7.alchemy.css
- login:
  - alchemy/alchemy
  - alchemy/alchemy_login
  - alchemy/alchemy_window
  - alchemy/jquery-ui-1.8.7.alchemy.css
- sitemap:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/jquery-ui-1.8.7.alchemy.css
- edit_page:
  - alchemy/alchemy
  - alchemy/elements
  - alchemy/contents
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/cropper
  - alchemy/flags
  - alchemy/jquery-ui-1.8.7.alchemy.css
- archive:
  - alchemy/alchemy
  - alchemy/alchemy_window
  - alchemy/alchemy_tooltip
  - alchemy/jquery-ui-1.8.7.alchemy.css