--- 
javascripts:
  - jquery
  - jquery-ui
  - jquery_ujs
  - jquery_plugins/jquery.dialogextend.min.js
  - jquery_plugins/jquery.in-place-edit.js
  - jquery_plugins/jquery.Jcrop.min.js
  - jquery_plugins/jquery.sb.min.js
  - jquery_plugins/jquery.scrollTo-1.4.2-min.js
  - jquery_plugins/jquery.ui.nestedSortable.js
  - jquery_plugins/jquery.ui.tabspaging.js
  - alchemy/alchemy
  - alchemy/alchemy.element_editor_selector
  - alchemy/alchemy.image_cropper
  - alchemy/alchemy.link_overlay
  - alchemy/alchemy.page_sorter
  - alchemy/alchemy.growler
  - swfupload/swfupload
  - swfupload/queue
  - swfupload/handlers
  - swfupload/fileprogress

stylesheets:
  - alchemy/alchemy
  - alchemy/elements
  - alchemy/flags
  - jquery-ui/alchemy.css
  - alchemy/jquery.Jcrop
  - alchemy/jquery.sb
