development:
  adapter: mysql
  encoding: utf8
  database: alchemy_dev
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: alchemy_dev_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: alchemy_dev_prod
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock
  #socket: /var/run/mysqld/mysqld.sock
