development:
  adapter: mysql
  encoding: utf8
  database: alchemy_1_0_beta_dev
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: alchemy_dev_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: usr_web6_6
  username: web6
  password: m0fwts5m
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
